#
#  CONTENT
#    test for a simple linux lib
#
#  AUTHOR
#    Norbert Stoeffler
#
#  DATE
#    2022-08-19
#
#  LANGUAGE
#    make
#
NBUILD =		../../..

GNU_LIB =		libsimple.a
GNU_LIB_SRCS =	foo.c

all::

clean::

include         $(NBUILD)/class/linux.mk
