# -*- tab-width: 4 -*-
#
#  CONTENT
#    default makefile for Linux (desktop)
#
#  AUTHOR
#    Norbert Stoeffler
#
#  DATE
#    2017-03-12
#
#  LANGUAGE
#    make
#
O-DIR :=	o-linux

include		../BUILD.mk
NBUILD :=	../$(NBUILD)

all::

clean::

NBMAKEFILE :=	Makefile ../BUILD.mk $(NBUILD)/flavors/$(O-DIR)/Makefile

include         $(NBUILD)/class/linux.mk



